### ISSUE TITLE
Identifying prime numbers in constant time and linear space.

### ISSUE THREAD

**Issue by yuvraj1803** [Sohoxic/GENERIC-DS-TEMPLATES#5]
This is Yuvraj Sakshith from PES University. Kindly assign me this issue.

**Comment by Sohoxic** [comment]
Sure, you can work on this issue. You have 24 hours starting from now.

**Comment by shreya2663** [comment]
can i do this

**Comment by Sohoxic** [comment]
@shreya2663 I've already assigned this to @yuvraj1803 and he's working on it, so I'd suggest you to work on a different issue of your choic if you want to contribute to this repo. You can create another PR for generic DS templates. Also  are you a hacktoberfest participant?

**Comment by Sohoxic** [comment]
@shreya2663 If you have a different approach for solving the same then you can proceed with the same.

**Comment by shreya2663** [comment]
Yes, I am a Hacktoberfest participant and I would like to work on another issue and contribute to this repo.
